parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/no-var-requires": 1
  "@typescript-eslint/explicit-module-boundary-types": 0